name: 'update-check'
description: 'Verify that update script works'
inputs:
  working-directory:
    description: 'Working directory'
  main-branch:
    description: 'Branch containing version to update from'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/../bin/update-check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        EXT_BRANCH: ${{ inputs.main-branch }}

